### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jialul** [MichaelLLi/evalITR#3]
# Causal ML updates
## General issues
- [ ] check package environment with [Windows](https://win-builder.r-project.org/)
- [x] write up the documentations 
- [x] add examples (micro-finance/star)
- [x] #28
- [x] #38 

### Documentation
- [x] finish documentations for test_itr
- [x] Roxygenize all the function and data
- [x] Simplify the examples

### Functions
- [x] check whether return outputs are consistent across all functions
- [x] check the SVM function
- [x] #8
- [x] #9
- [x] #17
- [x] #20
- [x] #26
- [x] https://github.com/MichaelLLi/evalITR/issues/24
- [x] #36

### Testing
- [x] #15
- [x] #14 
- [x] Run CRAN checks with [rhub](https://r-hub.github.io/rhub/articles/rhub.html)

### Output
- [x] create a summary(fit) page where we display some summary statistics (perhaps some PAPEs, fitting metrics and etc)
- [x] add summary of the plot_aupec output
- [x] #10
- [x] #11
- [x] #18
- [x] #27
- [x] #30
- [x] If only one alg is selected, do not print `PAPDp` summary statistics.

### Plotting
- [x] check the variance for AUPEC

## Other tasks
- [ ] #12
- [x] #13
- [ ] Check the tuning parameters for `caret` and `SuperLearner`

**Comment by kosukeimai** [comment]
What about adding some tests via [`testthat`](https://testthat.r-lib.org/)?

**Comment by jialul** [comment]
@kosukeimai will do!

**Comment by jialul** [comment]
May need to increase computation efficiency: http://adv-r.had.co.nz/Profiling.html

**Comment by xiaolong-y** [comment]
Could be useful applications for our paper or demo on the package website: https://github.com/gsbDBI/ExperimentData

**Comment by xiaolong-y** [comment]
> May need to increase computation efficiency: http://adv-r.had.co.nz/Profiling.html

Definitely good idea! Perhaps we can look into this once we finished writing all the functions planned for the current stage?

**Comment by xiaolong-y** [comment]
@jialul `summary` now shows statistics for `GATEcv` as well! Some new columns are upper and lower bound of confidence interval and group indicator for each estimate.  

<img width="835" alt="Screenshot 2022-09-21 at 18 21 38" src="https://user-images.githubusercontent.com/83687041/191467208-5b3929f3-61bc-40ef-9818-ea0e578631b1.png">
